name: CI-CD
on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: dotnet test
        run: dotnet test --configuration Release

      - name: dotnet publish
        run: dotnet publish src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj --configuration Release -o artifacts

      - uses: actions/upload-artifact@v4
        with:
          name: app-artifacts
          path: artifacts/

  deploy_dev:

    name: Deploy to dev
    needs: build
    uses: overlo65535/github-actions-demo/.github/workflows/step-deploy.yml@main # Reusable workflow which can live in a separate repository and shared across multiple repositories
    with:
      env: dev
      #artifact: "app-artifacts"
    secrets: inherit

#  deploy_prod:
#
#    name: Deploy to dev
#    needs: deploy_dev
#    uses: ./.github/workflows/step-deploy.yml
#    with:
#      env: prod
#    secrets: inherit
