name: Cron example
on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight

jobs:
  cron:
    name: cron sample
    runs-on: ubuntu-latest

    steps:
      - name: echo current date
        run: echo "The current date is $(date)"
