name: Cron example
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  cron:
    name: cron sample
    runs-on: ubuntu-latest

    steps:
      - name: echo current date
        run: echo "The current date is $(date)"
