name: Secrets Demo
on:
  pull_request:
    branches: ["main"]
env:
    KEY: "demokey"
jobs:
  secrets:
    name: secrets echo
    runs-on: ubuntu-latest

    steps:
      - name: echo env var
        run: echo "$KEY"
