name: Secrets Demo
on:
  pull_request:
    branches: ["main"]
env:
    KEY: "demokey" # global env var
jobs:
  secrets:
    name: secrets echo1
    runs-on: ubuntu-latest

    env:
      TEST_VAR: "test1" # job specific env var
    steps:
      - name: echo env var
        run: echo "$KEY and $TEST_VAR"

  secrets2:
    name: secrets echo2
    runs-on: ubuntu-latest

    env:
      TEST_VAR: "test2" # job specific env var
    steps:
      - name: echo env var
        run: echo "$KEY and $TEST_VAR"
