name: "Deploy - Step"

on:
  workflow_call:
    inputs:
      env:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: string
    secrets:
      AZURE_CLIENT_ID:
        description: "Azure client ID"
        required: true
      AZURE_TENANT_ID:
        description: "Azure tenant ID"
        required: true
      AZURE_SUBSCRIPTION_ID:
        description: "Azure subscription ID"
        required: true
jobs:
  deploy:

    name: Deploy to ${{ inputs.env }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-artifacts
          path: artifacts/

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy to Azure Web apps
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-gitactions-demo-${{ inputs.env }}
          package: artifacts/
