name: "Deploy - Step"

on:
  workflow_call:
    inputs:
      env:
        description: "Environment to deploy to"
        required: true
        type: string
      resource_group_name:
        description: "Azure resource group name"
        required: true
        type: string
      artifact:
        description: "Artifact to deploy"
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        description: "Azure client ID"
        required: true
      AZURE_TENANT_ID:
        description: "Azure tenant ID"
        required: true
      AZURE_SUBSCRIPTION_ID:
        description: "Azure subscription ID"
        required: true
jobs:
  deploy:

    name: Deploy to ${{ inputs.env }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact }}
          path: artifacts/

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run Bicep
        run: |
          az deployment group create \
            --name ${{ inputs.env }}-deployment-${{ github.run_number }} \
            --template-file infrastructure/main.bicep \
            --parameters infrastructure/environments/${{ inputs.env }}.bicepparam \
            --resource-group ${{ inputs.resource_group_name }} \
            --verbose

      # Deploy to Azure Web apps
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-gitactions-demo-${{ inputs.env }}
          package: artifacts/

      #- name: 'Swap slots for zero downtime deployment'
      #  run: |
      #    az webapp deployment slot swap --name app-gitactions-demo-${{ inputs.env }} --resource-group rg-gitactions-demo --slot staging --target-slot production --verbose
